version: "2"
services: 
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - localdev

  tomcat:
    image: tomcat:8.0
    ports:
      - "80:8080"
    networks:
      - localdev
    volumes:
      - ./build/libs/teamapi-1.0-SNAPSHOT.war:/usr/local/tomcat/webapps/api.war

networks:
  localdev:
    driver: bridge
